import ContentfulComponentSection from './ContentfulComponentSection/ContentfulComponentSection'
import ContentfulComponentRichTextGroup from './ContentfulComponentRichTextGroup/ContentfulComponentRichTextGroup'
import ContentfulComponentCarousel from './ContentfulComponentCarousel/ContentfulComponentCarousel'
import ContentfulComponentSpacer from './ContentfulComponentSpacer/ContentfulComponentSpacer'
import ContentfulComponentImageFullWidth from './ContentfulComponentImageFullWidth/ContentfulComponentImageFullWidth'
import ContentfulComponentIconCopyActionGroup from './ContentfulComponentIconCopyActionGroup/ContentfulComponentIconCopyActionGroup'
import ContentfulComponentVideoCopyActionGroup from './ContentfulComponentVideoCopyActionGroup/ContentfulComponentVideoCopyActionGroup'
import ContentfulComponentButton from './ContentfulComponentButton/ContentfulComponentButton'
import ContentfulComponentPartners from './ContentfulComponentPartners/ContentfulComponentPartners'
import ContentfulComponentStickyActionBar from './ContentfulComponentStickyActionBar/ContentfulComponentStickyActionBar'
import ContentfulComponentTerms from './ContentfulComponentTerms/ContentfulComponentTerms'
import ContentfulComponentNav from './ContentfulComponentNav/ContentfulComponentNav'

export default {
  ContentfulComponentSection,
  ContentfulComponentRichTextGroup,
  ContentfulComponentCarousel,
  ContentfulComponentSpacer,
  ContentfulComponentImageFullWidth,
  ContentfulComponentIconCopyActionGroup,
  ContentfulComponentVideoCopyActionGroup,
  ContentfulComponentButton,
  ContentfulComponentPartners,
  ContentfulComponentStickyActionBar,
  ContentfulComponentTerms,
  ContentfulComponentNav
}
