import ContentfulComponentSection from './ContentfulComponentSection/ContentfulComponentSection'
import ContentfulComponentRichText1X from './ContentfulComponentRichText1X/ContentfulComponentRichText1X'
import ContentfulComponentRichText2X from './ContentfulComponentRichText2X/ContentfulComponentRichText2X'
import ContentfulComponentCarousel from './ContentfulComponentCarousel/ContentfulComponentCarousel'
import ContentfulComponentSpacer from './ContentfulComponentSpacer/ContentfulComponentSpacer'
import ContentfulComponentImageFullWidth from './ContentfulComponentImageFullWidth/ContentfulComponentImageFullWidth'
import ContentfulComponentIconCopyActionGroup from './ContentfulComponentIconCopyActionGroup/ContentfulComponentIconCopyActionGroup'
import ContentfulComponentVideoCopyActionGroup from './ContentfulComponentVideoCopyActionGroup/ContentfulComponentVideoCopyActionGroup'
import ContentfulComponentButton from './ContentfulComponentButton/ContentfulComponentButton'
import ContentfulComponentPartners from './ContentfulComponentPartners/ContentfulComponentPartners'
import ContentfulComponentStickyActionBar from './ContentfulComponentStickyActionBar/ContentfulComponentStickyActionBar'
import ContentfulComponentTerms from './ContentfulComponentTerms/ContentfulComponentTerms'

export default {
  ContentfulComponentSection,
  ContentfulComponentRichText1X,
  ContentfulComponentRichText2X,
  ContentfulComponentCarousel,
  ContentfulComponentSpacer,
  ContentfulComponentImageFullWidth,
  ContentfulComponentIconCopyActionGroup,
  ContentfulComponentVideoCopyActionGroup,
  ContentfulComponentButton,
  ContentfulComponentPartners,
  ContentfulComponentStickyActionBar,
  ContentfulComponentTerms
}
