version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Deploy
          command:
            git config --global user.email 'circleci@circleci.com' &&
            git config --global user.name 'circleci' &&
            git commit --allow-empty -m 'circleci' &&
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git --force
